export const accessToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTVlZjBhMWEtOTFjYi00ZWVmLTlhZDEtZjI2MzcwZjQ5MDRiIiwiaWF0IjoxNzg4Mzc3OTQ1LCJleHAiOjE3ODg5ODI3NDV9.mki0SBWfUSP5EYkixmwnaOwhD9dlHnvVkKWUVrzk__g";
